training_arguments:
  evaluation_strategy: 'IntervalStrategy.epoch' # To change evaluation strategy comment out the line and uncomment the next line two lines
  # eval_steps: 500
  # evaluation_strategy: 'steps'    # evaluate after some number of steps
  output_dir: './results'          # output directory
  save_total_limit: 5             # number of maximum checkpoints to save
  num_train_epochs: 2             # number of training epochs
  per_device_train_batch_size: 32 # batch size for training
  per_device_eval_batch_size: 32  # batch size for evaluation
  warmup_steps: 500               # number of warmup steps for learning rate scheduler
  weight_decay: 0.01              # strength of weight decay
  logging_dir: './logs'           # directory for storing logs
  logging_steps: 10
  load_best_model_at_end: True
  metric_for_best_model: 'loss'    # metric to use for saving best model
  report_to: 'wandb'               # report to wandb


